manifest:
  remotes:
    - name: zmkfirmware
      url: https://github.com/zmkfirmware/zmk
    - name: petejohanson
      url: https://github.com/petejohanson/zmk
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-rebased-v4.0
      import: app/west.yml
  self:
    path: config